{
 "title": "Merged Kubernetes Dashboard",
 "description": "This dashboard can help troubleshooting issue in k8s cluster at cluster, node and namespace level.",
 "tags": [
  "kubernetes",
  "k8s",
  "namespace"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_created,node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(kube_namespace_labels)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "kube_pod_container_info{namespace=\"$namespace\"}"
    }
   },
   {
    "name": "duration",
    "query": "10m,30m,1h,2h,6h,12h,1d,2d,5d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Namespaces memory usage",
   "type": "bargauge",
   "description": "네임스페이스별 사용량 현황판 ",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_usage_bytes{container!=\"pod\",image!=\"\"})/1048576"
    }
   ]
  },
  {
   "title": "Etcd has a leader?",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "max(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "Members State",
   "type": "table",
   "description": "Controlplane 의 컴포넌드들의 리더 상태 현황판",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "targets": [
    { "expr": "leader_election_master_status" }
   ]
  },
  {
   "title": "The number of leader changes seen",
   "type": "stat",
   "description": "etcd leader 변경 횟수 현황",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total)"
    }
   ]
  },
  {
   "title": "Running Kubelets",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "title": "Cluster SLO and Error budget", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Cluster control plane SLO over $duration",
   "type": "stat",
   "description": "주요 컴포넌트(API 서버, 컨트롤러 매니저, 스케줄러 등)의 성능 또는 가용성에 대한 목표 값, 6시간 동안의 측정 기준을 의미",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.cilium.*|.*.etcd.*\"})\n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.cilium.*|.*.flannel.*|.*.etcd.*\"}))[$duration:5m])\n)"
    }
   ]
  },
  { "title": "Overall cluster status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "cluster  node status",
   "type": "stat",
   "description": "클러스터에 조인된 각 노드들의 Ready 상태 체크\n",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_node_status_condition{status=\"true\",condition=\"Ready\"}) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Nodes ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "$node uptime",
   "type": "stat",
   "description": "노드 업타임(리부팅) 된 시간 체크\n",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " (\n ((time() - node_boot_time_seconds + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})) \nand \nON() kube_node_status_condition{status=\"true\",condition=\"Ready\",node=\"$node\"} == 1 \n) ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Namespaces ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": " count(kube_namespace_created)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Time synced",
   "type": "stat",
   "description": "노드의 시간 동기화 상태 체크 현황판\n",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_timex_sync_status) * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"} ",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "cluster  node details",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 17 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{node}}" },
    {
     "expr": " (count by (node)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))"
    },
    {
     "expr": "((label_replace((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))  -  (label_replace((node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))) /  (label_replace((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\")) "
    },
    {
     "expr": "max\n  by(node) (max by(instance) (kubelet_running_pod_count{job=\"kubelet\",metrics_path=\"/metrics\"})\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\n"
    },
    {
     "expr": "sum by (node)(label_replace(instance:node_cpu:ratio + on(instance) group_left(nodename) \nnode_uname_info,\"node\",\"$1\",\"nodename\", \"(.+)\") ) / sum by (node)(kube_node_status_capacity{resource=\"cpu\"})"
    },
    { "expr": "kube_node_role" }
   ]
  },
  {
   "title": "API server status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  up{job=\"apiserver\"},\n  \"instance\", \"$1\", \"instance\", \"(.*):.*\"\n)\n* on(instance) group_left(node) (\n  label_replace(\n    max by(internal_ip, node) (\n      kube_node_info{job=\"kube-state-metrics\", node=~\".*master.*\"}\n    ),\n    \"instance\", \"$1\", \"internal_ip\", \"(.*)\"\n  )\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "API server certificate expiration time remaninig",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_client_certificate_expiration_seconds_count{job=\"apiserver\"}\n  > 0 and on(job) histogram_quantile(0.01, sum by(job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job=\"apiserver\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}